### ISSUE TITLE
Petya Samples

### ISSUE THREAD

**Issue by rdev5** [leo-stone/hack-petya#1]
Having never actually been infected with ransomware or seen a sample of it as of yet, would you happen to have any samples available of perhaps an encrypted text document that we could try this on?

Or is [`src.txt`](https://github.com/leo-stone/hack-petya/blob/master/main.go#L149) a sample?

**Comment by leo-stone** [comment]
src.txt and nonce.txt are the only samples i've got, it's the actual data from my case
