### ISSUE TITLE
How to get these bytes

### ISSUE THREAD

**Issue by casmssm** [leo-stone/hack-petya#13]
Hi, please help me.
I want to get the data and nonce, but how i do this on Linux?
Im trying using DD and XXD.

**Comment by leo-stone** [comment]
dd if=path of your disk or image   of=nonce.txt bs=1 skip=27681 count=8
dd if=path of your disk or image   of=src.txt bs=1 skip=28160 count=512

bs=1 means blocksize one byte
skip=27681 is (54x512)+33
skip=28160 is (55x512)+0

hope it helps

**Comment by casmssm** [comment]
Thank you, very much.
I get it!
Next step is to run Main.go file, but what is your language? Python?

**Comment by leo-stone** [comment]
> Thank you, very much.
> I get it!
> Next step is to run Main.go file, but what is your language? Python?

https://golang.org/
