### ISSUE TITLE
Don't use genetic algorithms

### ISSUE THREAD

**Issue by klondi** [leo-stone/hack-petya#3]
Hi @leo-stone I have published a blogpost with a propper cryptanalisys of the Salsa-20 version used by Petya as it is implemented by your code. In the end you'll find a more efficient method to get back the key (in O(1)) without the need of using genetic algorithms. I hope it helps.

The blogpost can be found at https://klondike.es/klog/2016/04/12/cryptanalyzing-petya/

**Comment by leo-stone** [comment]
Hi klondike, I've accomplished what I needed. I am not a cryptographer, and I have many other things waitn 4 me. I won't touch any of this code anymore .... But thank you very much for the analysis, that is the part I did not even remotely have the time for.....
