### ISSUE TITLE
Working Solution outdated or updated?

### ISSUE THREAD

**Issue by webtron101** [leo-stone/hack-petya#4]
If you managed to catch petya at stage 1 and you know the rest of the steps you can use this online decrypter to get the key...
https://petya-pay-no-ransom-mirror1.herokuapp.com

This is derived from this link
https://hshrzd.wordpress.com/2016/03/31/petya-key-decoder/

LS please let us know if we (as in the world) can discard this now ?
Thanks for your contrib ...

**Comment by leo-stone** [comment]
I do not quite understand, what do you want to discard???

**Comment by webtron101** [comment]
Apologies for the language barrier

What I meant to ask is whether those links can still be used or will that whole process no longer be necessary after using the key output from your code?

**Comment by leo-stone** [comment]
Oh, ok, well the code here gives you the key, just the same as https://petya-pay-no-ransom-mirror1.herokuapp.com.

So if you run the program locally on your machine, you do not need to visit https://petya-pay-no-ransom-mirror1.herokuapp.com.

Does this answer your question?

**Comment by webtron101** [comment]
Yes. Thank you very much.
