### ISSUE TITLE
Endless decoding !?!

### ISSUE THREAD

**Issue by Marook332** [leo-stone/hack-petya#5]
First of all, thank you for this great piece of code !

I downloaded the source and setup a development machine running ubuntu 14.04. After that, i extracted the needed sectors of the hdd with the petya-extractor tool. 

If i run the code, it will start to decrypt it but it decodes and decodes and no i can't see a result. The lowest score i get it 86 and it seems after that it will start over... any ideas ?

Sample output :
pxCxsxgxKxBxDxBx score: 100  (lower is better)
pxCxUxDxCxBxDxBx score: 99  (lower is better)
pxCxUx8xCxBxDxBx score: 97  (lower is better)
pxCxNx3xCxBxDxBx score: 96  (lower is better)
pxCxNx3xCx2xDxBx score: 95  (lower is better)
pxExuxixSxBxDxBx score: 91  (lower is better)
pxCx4x8xsxBxDxBx score: 90  (lower is better)
^Csignal: interrupt

I cancled it after about 10 mins or so...

Edit2: Same with the compiled binaries, even with your bins i've found here on github...

**Comment by leo-stone** [comment]
do not base64 encode the data, if you are using the txt files!!! just plain binary data ....

was that the problem ....?

**Comment by Marook332** [comment]
Nice, thats it ! Thx alot !!!
