### ISSUE TITLE
Petya 2.0

### ISSUE THREAD

**Issue by Udo4711** [leo-stone/hack-petya#9]
Hello,

i have to pcs which were infected by a new version of petya and I was wondering if your tool also work with ne version?

I just used the PetyaExtraktor.exe which worked the last time and tried to generate the key withe the website https://petya-pay-no-ransom.herokuapp.com/, but this time it doesn't work. 

Have you heard from the new version of petya? Can you something about it?

Thanks
Udo

**Comment by leo-stone** [comment]
Hi Udo, it could be a new version, but I don't have the time to investigate.
